Create sysmon_susp_devilstongue_CVE_2021_31979_CVE_2021_33771.yml
SigmaHQ/sigma pull request #1706
Opened 2021-07-16 15:09 UTC by BlackB0lt

2021-07-16 17:16 UTC, BlackB0lt commented
@Neo23x0 Could you help to resolve my error in test-sigma?

2021-07-16 17:42 UTC, frack113 requested changes
Hi, some change to try again

2021-07-16 17:42 UTC, frack113 commented on rules/windows/sysmon/sysmon_cve_2021_31979_cve_2021_33771_exploits.yml
> +title: CVE-2021-31979 CVE-2021-33771 Exploits by Sourgum
```
action: global
title: CVE-2021-31979 CVE-2021-33771 Exploits by Sourgum
```

2021-07-16 17:42 UTC, frack113 commented on rules/windows/sysmon/sysmon_cve_2021_31979_cve_2021_33771_exploits.yml
> +falsepositives:
As falsepositives and level are commun (global) for all detection move before the first `---`

2021-07-16 17:42 UTC, frack113 commented on rules/windows/sysmon/sysmon_cve_2021_31979_cve_2021_33771_exploits.yml
> +        EventID: 13
For sysmon don't Eventid use `category: registry_event`

2021-07-16 17:42 UTC, frack113 commented on rules/windows/sysmon/sysmon_cve_2021_31979_cve_2021_33771_exploits.yml
> +logsource:
```
---
logsource:
```

2021-07-16 18:56 UTC, frack113 commented on rules/windows/sysmon/sysmon_cve_2021_31979_cve_2021_33771_exploits.yml
> +    service: sysmon
Please remove `service` as it is not need.
When you convert `registry_event` and `windows` it give sysmon chanel and the good eventid in the query.
Thanks

2021-07-17 02:26 UTC, BlackB0lt commented on rules/windows/sysmon/sysmon_cve_2021_31979_cve_2021_33771_exploits.yml
> +    service: sysmon
Done

2021-07-17 04:52 UTC, frack113 approved these changes

2021-07-17 07:46 UTC, merged