sysmon_dns_over_https_enabled.yml
SigmaHQ/sigma pull request #1724
Opened 2021-07-22 16:05 UTC by austinsonger

2021-07-22 16:20 UTC, frack113 requested changes
missing a space

2021-07-22 16:20 UTC, frack113 commented on rules/windows/registry_event/sysmon_dns_over_https_enabled.yml
> +id:04b45a8a-d11d-49e4-9acc-4a1b524407a5
id: 04b45a8a-d11d-49e4-9acc-4a1b524407a5

2021-07-22 17:32 UTC, frack113 requested changes
Sorry , some more change

2021-07-22 17:32 UTC, frack113 commented on rules/windows/registry_event/sysmon_dns_over_https_enabled.yml
> +references:
date: 2021/07/22

2021-07-22 17:32 UTC, frack113 commented on rules/windows/registry_event/sysmon_dns_over_https_enabled.yml
> +- "Unlikely"
\" not need

2021-07-22 17:32 UTC, frack113 commented on rules/windows/registry_event/sysmon_dns_over_https_enabled.yml
> +level: "medium"
level: medium

2021-07-23 07:52 UTC, Neo23x0 commented
Thanks

2021-07-23 07:52 UTC, merged