Create sysmon_disabled_pua_protection_on_microsoft_defender.yml
SigmaHQ/sigma pull request #1775
Opened 2021-08-04 16:30 UTC by austinsonger

I don't know if this will work how I want it to.

```
[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender]
"PUAProtection"=dword:00000000
```

2021-08-04 17:50 UTC, frack113 requested changes
Just a fast review

2021-08-04 17:50 UTC, frack113 commented on rules/windows/registry_event/sysmon_disabled_pua_protection_on_microsoft_defender.yml
> +    product: windows
There is a tabulation \t after windows to remove

2021-08-04 17:50 UTC, frack113 commented on rules/windows/registry_event/sysmon_disabled_pua_protection_on_microsoft_defender.yml
> +    condition: selection
There is a tabulation \t after selection to remove

2021-08-04 17:50 UTC, frack113 commented on rules/windows/registry_event/sysmon_disabled_pua_protection_on_microsoft_defender.yml
> +        TargetObject|endswith:
`TargetObject|endswith: PUAProtection` works well as only 1 value

2021-08-04 18:09 UTC, frack113 requested changes
need to test on a VN but sure for HKLM

2021-08-04 18:09 UTC, frack113 commented on rules/windows/registry_event/sysmon_disabled_pua_protection_on_microsoft_defender.yml
> +        TargetObject|contains: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows Defender'
on sysmon sould be `HKLM\SOFTWARE\Policies\Microsoft\Windows Defender\PUAProtection`

2021-08-04 18:40 UTC, frack113 commented
Hi,
Add tags `attack.t1562.001` https://attack.mitre.org/techniques/T1562/001/ Impair Defenses: Disable or Modify Tools 
Thanks

2021-08-05 08:50 UTC, frack113 approved these changes

2021-08-05 12:03 UTC, StevenDias33 approved these changes

2021-08-05 13:42 UTC, merged