Adding detection rule for esentutl utility
SigmaHQ/sigma pull request #1780
Opened 2021-08-05 20:57 UTC by Sam0x90

Used by Conti affiliates to target NTDS file and MSEdge info.

2021-08-06 04:49 UTC, frack113 requested changes

2021-08-06 04:49 UTC, frack113 commented on rules/windows/process_creation/Conti_esentutl.yaml
> +title: Detection of esentutl aka Extensible Storage Engine Utilities to gather credentials
`title: Gather Credentials with Esentutl Aka Extensible Storage Engine Utilities`
title don't start with detect and word are capitalization

2021-08-06 04:49 UTC, frack113 commented on rules/windows/process_creation/Conti_esentutl.yaml
> +	- https://attack.mitre.org/software/S0404/
Remove tab as it is a yaml file

2021-08-06 04:49 UTC, frack113 commented on rules/windows/process_creation/Conti_esentutl.yaml
> +        CommandLine|contains:
`CommandLine|contains: 'esentutl'`
Only 1 value no need a list

2021-08-06 04:49 UTC, frack113 commented on rules/windows/process_creation/Conti_esentutl.yaml
> +	- CommandLine
Remove tab as it is a yaml file

2021-08-06 04:49 UTC, frack113 commented on rules/windows/process_creation/Conti_esentutl.yaml
> +    condition: all of them
Other way:
```yaml
   selection:
        CommandLine|contains|all:
            - 'esentutl'
            - ' /p'
    condition: selection
```
Fisrt way : `(event.code:"1" AND winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational" AND process.command_line.keyword:*esentutl* AND process.command_line.keyword:*\ \/p*)`
Other way : alfer `(event.code:"1" AND winlog.channel:"Microsoft\-Windows\-Sysmon\/Operational" AND process.command_line.keyword:*esentutl* AND process.command_line.keyword:*\ \/p*)`
Same result

2021-08-06 17:55 UTC, frack113 requested changes

2021-08-06 17:55 UTC, frack113 commented on rules/windows/process_creation/process_susp_esentutl_params.yaml
> +    condition: all of them
`condition: selection`

2021-08-06 19:32 UTC, Sam0x90 commented
Thanks guys for the help!

2021-08-07 13:52 UTC, frack113 approved these changes

2021-08-07 14:23 UTC, merged