Adding Various Rules To Monitor Process Creations in Sysmon, Event Logs & EDR
SigmaHQ/sigma pull request #1956
Opened 2021-08-31 03:53 UTC by Cyb3rEng

Rules added were inspired ideas by :
https://github.com/vadim-hunter/Detection-Ideas-Rules/blob/main/Threat%20Intelligence/The%20DFIR%20Report/20210329_Sodinokibi_(aka_REvil)_Ransomware.yaml

Completed in contribution to TheDFIRReport: https://thedfirreport.com/2021/03/29/sodinokibi-aka-revil-ransomware/

Regards

2021-08-31 04:44 UTC, frack113 commented
Hello,
thanks for the work.
before I can approve please
 - check the wiki for [title](https://github.com/SigmaHQ/sigma/wiki/Rule-Creation-Guide#title) 
 - increment '2 or 4 spaces' tags,references, list  for a better human reading
 - falsepositives use `  - unknown` but not "" 
 - author should better be `Vadim Khrykov (Theatintel) , Cyb3rEng (rule)`
 - don't use description in detection section use `# usefull informations`
 - remove `service: Sysmon` and 'selection1' as there is alreaday [windows + process_creation](https://github.com/SigmaHQ/sigma/blob/a5c6bbe04d4ca947d98079377b26ca48866e4d3f/tools/config/generic/sysmon.yml#L5)
 
I just checked the formalism.
good correction

2021-09-01 03:14 UTC, Cyb3rEng commented
Hello, 

Sounds good to me and thank you for the feedback, I will work on it. 

Regards

2021-09-06 19:16 UTC, frack113 commented
Hi,
make some fix (convert to LF ) to pass the yaml test .
When use `category: process_creation` don't use EventID as it is add when use tools/config/generic/sysmon.yml or tools/config/generic/windows-audit.yml in the convertion. 
Check Monitor_LOLBins_Process_Creations_by_Office_applications.yml for exemple.

2021-09-08 03:36 UTC, Cyb3rEng commented
Hello,

Thank you for pointing out those mistakes to me. Hopefully, those modifications were in line with the requirements. 

Regards

2021-09-08 07:51 UTC, frack113 commented
Hi,
Check the category : 
`process_creation` is only for eventid 1 or 4688.
EventID 11 is `file_event`  , 12-13-14 `registry_event`
View tools/config/generic/sysmon.yml for more details

2021-09-09 03:30 UTC, Cyb3rEng commented
Hello,

thank you again for your patience. I have completed the changes to the best of my knowledge and fixed more issues that I noticed along the way. 

Regards

2021-09-09 04:35 UTC, frack113 commented on rules/windows/process_creation/Monitor_Office_Applications_Spawning_WMI_command-line.yml
> +  - ParentImage:
Only one so no `-`

2021-09-09 04:41 UTC, frack113 requested changes

2021-09-09 04:41 UTC, frack113 commented on rules/windows/process_creation/Monitor_WMI_Win32_Process Create_command_execution_by_Office_Applications.yml
> +    - Image|endswith:
only one so no `-`

2021-09-09 04:41 UTC, frack113 commented on rules/windows/process_creation/Monitor_executable_and_script_files_creation_by_Office_applications_using_file_extentions.yml
> +title: Executable and Files creation by Office Applications
Title must respect [wiki](https://github.com/SigmaHQ/sigma/wiki/Rule-Creation-Guide#title)  so `Creation`

2021-09-09 04:42 UTC, frack113 commented
hi,
 - attack.defence_evasion is `attack.defense_evasion` [mitre](https://attack.mitre.org/tactics/TA0005/)
 - rule must have a id unique [get one here](https://www.uuidgenerator.net/)
 - Date is `date`

2021-09-09 04:43 UTC, frack113 commented on rules/windows/process_creation/Monitor_Office_Applications_Spawning_WMI_command-line.yml
> +  - ParentImage:
```yaml
 selection2:
   ParentImage:
```

2021-09-10 02:56 UTC, Cyb3rEng commented on rules/windows/process_creation/Monitor_Office_Applications_Spawning_WMI_command-line.yml
> +  - ParentImage:
Completed fix on next commit

2021-09-10 03:02 UTC, Cyb3rEng commented on rules/windows/sysmon/Office_Applications_Spawning_WMI_command-line.yml
> +    - ParentPrcessName|endswith:
Completed fix on next commit

2021-09-10 03:04 UTC, Cyb3rEng commented on rules/windows/process_creation/Monitor_WMI_Win32_Process Create_command_execution_by_Office_Applications.yml
> +    - Image|endswith:
Completed fix on next commit

2021-09-10 03:09 UTC, Cyb3rEng commented on rules/windows/process_creation/Monitor_executable_and_script_files_creation_by_Office_applications_using_file_extentions.yml
> +title: Executable and Files creation by Office Applications
Completed fix on next commit

2021-09-10 03:46 UTC, Cyb3rEng commented
Hello,

All reviews were changed and re-committed. 

Regards

2021-09-10 04:49 UTC, frack113 approved these changes

2021-09-10 04:59 UTC, frack113 commented
HI, there are duplicate rule

- 'rules/windows/sysmon/Monitor_LOLBins_process_creations_with_Wmiprvse_parent_process.yml',   <--to remove
- 'rules/windows/process_creation/Monitor_LOLBins_process_creations_with_Wmiprvse_parent_process.yml'

and

- 'rules/windows/sysmon/Monitor_LOLBins_Process_Creations_by_Office_applications.yml'          <--to remove
- 'rules/windows/process_creation/Monitor_LOLBins_Process_Creations_by_Office_applications.yml'

2021-09-10 05:10 UTC, Cyb3rEng commented
hello

thank you :) , duplicate rules are now removed. 

Regards

2021-09-10 08:47 UTC, merged