Rule Update (Batch 2)
SigmaHQ/sigma pull request #3020
Opened 2022-05-16 21:03 UTC by nasbench

- Added 5 more PowerShell scripts for the rule "file_event_win_powershell_exploit_scripts.yml"
- Created a new rule for "certoc" lolbin to cover the "Download" option as described in the LOLBAS project
- Created a specific rule for the "IEExec" lolbin to cover the "Download" option as described in the LOLBAS Project
- Updated some rules to use "OriginalFileName" in addition to the "Image" selection
- Updated some rules to increase coverage.

2022-05-17 12:08 UTC, frack113 requested changes
Some check

2022-05-17 12:08 UTC, frack113 commented on rules/windows/process_creation/proc_creation_win_certoc_download.yml
> +
```
tags:
    - attack.command_and_control
    - attack.t1105
```

2022-05-17 12:08 UTC, frack113 commented on rules/windows/process_creation/proc_creation_win_cmdkey_recon.yml
> +        - OriginalFileName: 'CertOC.exe'
`OriginalFileName: 'cmdkey.exe'`

2022-05-17 13:42 UTC, frack113 commented on rules/windows/process_creation/proc_creation_win_lolbas_configsecuritypolicy.yml
> +        - OriginalFileName: 'ConfigSecurityPolicy'
`OriginalFileName: 'ConfigSecurityPolicy.exe'`

2022-05-17 13:42 UTC, frack113 commented on rules/windows/process_creation/proc_creation_win_lolbas_extrac32.yml
>      lolbas:
Here we look for "Extracts the source CAB file..."
```
 selection_lolbas:
        - CommandLine|contains: extrac32.exe
        - Image|endswith: '\extrac32.exe'
        - OriginalFileName: 'extrac32.exe'
 selection_archive:
       - CommandLine|contains: '.cab'
 selection_options:
       CommandLine|contains:
            - /C
            - /Y
            - ' \\'
condition: all of selection_*
```

2022-05-17 13:42 UTC, frack113 commented on rules/windows/process_creation/proc_creation_win_shadow_copies_deletion.yml
> +        OriginalFileName: 'VSSADMIN.EXE'
```
    selection3_img:
        - Image|endswith: '\vssadmin.exe'
        - OriginalFileName: 'VSSADMIN.EXE'
````

2022-05-17 14:47 UTC, frack113 approved these changes

2022-05-18 05:05 UTC, Neo23x0 approved these changes

2022-05-18 05:05 UTC, merged