Create azure_app_credential_added.yml
SigmaHQ/sigma pull request #3049
Opened 2022-05-26 02:16 UTC by MarkMorow

App Credential Add rule

2022-05-26 16:39 UTC, MarkMorow commented
@frack113 ok I think it's fixed.

2022-05-26 17:12 UTC, frack113 requested changes

2022-05-26 17:12 UTC, frack113 commented on rules/cloud/azure/azure_app_credential_added.yml
> +title: Added credentials to existing application
`title: Added Credentials to Existing Application` https://github.com/SigmaHQ/sigma/wiki/Rule-Creation-Guide#common-pitfalls

2022-05-26 17:12 UTC, frack113 commented on rules/cloud/azure/azure_app_credential_added.yml
> +level: High
`level: high` https://github.com/SigmaHQ/sigma/wiki/Specification#level

2022-05-26 17:12 UTC, frack113 commented on rules/cloud/azure/azure_app_credential_added.yml
> +status: expiramental
`status: experimental` https://github.com/SigmaHQ/sigma/wiki/Specification#status-optional

2022-05-26 19:46 UTC, MarkMorow commented
@frack113 ok sorry, added a bit more after reviewing your guide. Thanks!

2022-05-27 04:56 UTC, frack113 approved these changes

2022-05-27 05:01 UTC, merged