Create win_susp_vuln_cve_2022_21919_or_cve_2021_34484.yml
SigmaHQ/sigma pull request #3384
Opened 2022-08-16 15:57 UTC by sorchaa

2022-08-17 04:51 UTC, frack113 commented
HI from [Microsoft-Windows-User%20Profiles%20Service.xml](https://github.com/nasbench/EVTX-ETW-Resources/blob/main/ETWProvidersManifests/WindowsServer/2022/WindowsServer2022_21H2_Standard_20220719_20348.825/WEPExplorer/Microsoft-Windows-User%20Profiles%20Service.xml) : 
[eventid 1511](https://github.com/nasbench/EVTX-ETW-Resources/blob/45fd5be71a51aa518b1b36d4e1f36af498084e27/ETWProvidersManifests/WindowsServer/2022/WindowsServer2022_21H2_Standard_20220719_20348.825/WEPExplorer/Microsoft-Windows-User%20Profiles%20Service.xml#L742) make sense
[eventid 1515](https://github.com/nasbench/EVTX-ETW-Resources/blob/45fd5be71a51aa518b1b36d4e1f36af498084e27/ETWProvidersManifests/WindowsServer/2022/WindowsServer2022_21H2_Standard_20220719_20348.825/WEPExplorer/Microsoft-Windows-User%20Profiles%20Service.xml#L794) could give FP

2022-08-17 09:12 UTC, sorchaa commented on rules/windows/builtin/system/win_susp_vuln_cve_2022_21919_or_cve_2021_34484.yml
> +status: test
i replaced by experimental

2022-08-17 09:12 UTC, sorchaa commented on rules/windows/builtin/system/win_susp_vuln_cve_2022_21919_or_cve_2021_34484.yml
> +  service: Profile Service
I replaced by service: application

2022-08-17 09:13 UTC, sorchaa commented on rules/windows/builtin/system/win_susp_vuln_cve_2022_21919_or_cve_2021_34484.yml
> +      System.ProviderName: 'Microsoft-Windows-User Profiles Service'
I replaced by Providername

2022-08-17 09:14 UTC, sorchaa commented
Hi,
I did the modifications you suggested.

2022-08-17 17:35 UTC, frack113 requested changes

2022-08-17 17:35 UTC, frack113 commented on rules/windows/builtin/system/win_susp_vuln_cve_2022_21919_or_cve_2021_34484.yml
> +detection:
```yaml
detection: 
    selection:
        EventID: 1511                      
        ProviderName: 'Microsoft-Windows-User Profiles Service'
    condition: selection
```

2022-08-17 17:39 UTC, frack113 requested changes

2022-08-17 17:39 UTC, frack113 commented on rules/windows/builtin/system/win_susp_vuln_cve_2022_21919_or_cve_2021_34484.yml
> +title: Suspicious usage of CVE 2022_21919 or CVE_2021_34484
`title: Suspicious Usage of CVE 2022_21919 or CVE_2021_34484`
https://github.com/SigmaHQ/sigma/wiki/Rule-Creation-Guide#title

2022-08-17 17:39 UTC, frack113 commented on rules/windows/builtin/system/win_susp_vuln_cve_2022_21919_or_cve_2021_34484.yml
> +date: 22/08/16
`date: 2022/08/16`
https://github.com/SigmaHQ/sigma/wiki/Rule-Creation-Guide#date

2022-08-17 17:41 UTC, frack113 commented
You can run `python3 tests/test_rules.py` to test before push

2022-08-18 06:56 UTC, sorchaa commented
Hi,
It's updated.

2022-08-18 07:21 UTC, sorchaa commented
test_rules.py passed

2022-08-18 16:24 UTC, merged