Create proc_creation_win_susp_secedit.yml
SigmaHQ/sigma pull request #3725
Opened 2022-11-24 11:10 UTC by blueteam0ps

This was created based off my research https://blueteamops.medium.com/secedit-and-i-know-it-595056dee53d

2022-11-25 09:38 UTC, nasbench commented on rules/windows/process_creation/proc_creation_win_susp_secedit.yml
> +level: medium
```suggestion
logsource:
    category: process_creation
    product: windows
detection:   
    selection_img:
        - Image|endswith: '\secedit.exe'
        - OriginalFileName: 'SeCEdit'
    selection_flags_discovery:
        CommandLine|contains|all:
            - '/export'
            - '/cfg'
    selection_flags_configure:
        CommandLine|contains|all:
            - '/configure'
            - '/db'
    filter:
        SubjectUserName|endswith: '$'
    condition: selection_img and (1 of selection_flags_*) and not filter
falsepositives:
    - Legitimate administrative use
level: medium
```

2022-11-25 09:38 UTC, nasbench commented on rules/windows/process_creation/proc_creation_win_susp_secedit.yml
> +    - https://blueteamops.medium.com/secedit-and-i-know-it-595056dee53d
```suggestion
    - https://blueteamops.medium.com/secedit-and-i-know-it-595056dee53d
    - https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/secedit
```

2022-11-25 09:38 UTC, nasbench commented on rules/windows/process_creation/proc_creation_win_susp_secedit.yml
> +description: Detects potential suspicious behaviour using secedit.exe
```suggestion
description: Detects potential suspicious behaviour using secedit.exe. Such as exporting or modifying the security policy
```

2022-11-25 09:39 UTC, nasbench commented
Thanks for the PR. What do you think about the `/import` flag? Can it be used in a suspicious manner to import a modified db/config?

2022-11-25 11:41 UTC, blueteam0ps commented
> Thanks for the PR. What do you think about the `/import` flag? Can it be used in a suspicious manner to import a modified db/config?

Good call out for that. However, import just imports the ini template to the ese db. At that stage it doesn't make any impact to the system. The only way to apply the config that is in the ese is by using the /configure switch. That is already covered.

2022-11-25 13:22 UTC, nasbench reviewed
Approved after changes

2022-11-25 13:22 UTC, nasbench commented on rules/windows/process_creation/proc_creation_win_susp_secedit.yml
> +    - attack.T1082
```suggestion
tags:
    - attack.discovery
    - attack.persistence
    - attack.defense_evasion
    - attack.credential_access
    - attack.privilege_escalation
    - attack.t1562.002
    - attack.t1547.001
    - attack.t1546.007
    - attack.t1505.005
    - attack.t1556.002
    - attack.t1562
    - attack.t1574.007
    - attack.t1564.002
    - attack.t1546.008
    - attack.t1546.007
    - attack.t1547.014
    - attack.t1547.010
    - attack.t1547.002
    - attack.t1557
    - attack.t1082
```

2022-11-25 13:22 UTC, nasbench commented on rules/windows/process_creation/proc_creation_win_susp_secedit.yml
> +title: Potential suspicious activity using secedit.exe
```suggestion
title: Potential Suspicious Activity Using SeCEdit
```

2022-11-29 22:49 UTC, nasbench requested changes

2022-11-29 22:49 UTC, nasbench commented on rules/windows/process_creation/proc_creation_win_susp_secedit.yml
> +    - attack.t1546.007
```suggestion
```

2022-12-02 10:58 UTC, nasbench approved these changes

2022-12-02 12:21 UTC, merged