Create azure_ad_azurehound_discovery.yml
SigmaHQ/sigma pull request #3762
Opened 2022-12-07 10:19 UTC by blueteam0ps

Adding AzureHound detection via default UA string.

2022-12-07 11:28 UTC, nasbench requested changes

2022-12-07 11:28 UTC, nasbench commented on rules/cloud/azure/azure_ad_azurehound_discovery.yml
> +        userAgent|starswith: 'azurehound'
```suggestion
        userAgent|startswith: 'azurehound'
```

2022-12-07 11:28 UTC, nasbench commented on rules/cloud/azure/azure_ad_azurehound_discovery.yml
> +        ResultType: '0'
```suggestion
        ResultType: 0
```

2022-12-07 14:55 UTC, frack113 requested changes

2022-12-07 14:55 UTC, frack113 commented on rules/cloud/azure/azure_ad_azurehound_discovery.yml
> +    selection_ua:
```suggestion
    selection:
```
as condition use selection

2022-12-08 06:28 UTC, blueteam0ps commented on rules/cloud/azure/azure_ad_azurehound_discovery.yml
> +        userAgent|startswith: 'azurehound'
Ye so the actual UA comes as azurehound followed by the version no . Hence starts with. But I get your point to have it match on any as it is a low FP UA string.

2022-12-08 09:04 UTC, nasbench approved these changes

2022-12-08 19:19 UTC, frack113 approved these changes

2022-12-08 19:21 UTC, merged