Add common childprocess filter for OneNote
SigmaHQ/sigma pull request #4018
Opened 2023-02-07 21:08 UTC by signus

Slight reoranization of the rule with an additional relevant reference.

Additionally adds the `filter_common_childproc` filter to `proc_creation_win_susp_microsoft_onenote_child_process.yml` for common processes that are launched from OneNote. OneNote will commonly launch `Teams.exe -Embedded` for opening documents in Teams, as well as `FileCoAuth.exe` when people are sharing/editing specific documents through OneNote. For some organizations these can create enough noise that it may be warranted to filter out as a part of the rule. Thusfar malicious execution for `Teams.exe` and `FileCoAuth.exe` have not been observed.

2023-02-07 21:33 UTC, nasbench commented
Hi,

Thanks for the suggestion and contribution. I would like more information before we can add this.

- What are the usual paths for the `FileCoAuth` process and the typical command line it's launched with?
- Is `Teams.exe -Embedded` the only command line observed? 

If you have public references for these FPs or any additional logs you could provide (that would be much appreciated)

2023-02-08 05:36 UTC, frack113 requested changes

2023-02-08 05:36 UTC, frack113 commented on rules/windows/process_creation/proc_creation_win_susp_microsoft_onenote_child_process.yml
> +---
```suggestion

```
https://yaml.org/spec/1.2.2/ "YAML uses three dashes (“---”) to separate [directives](https://yaml.org/spec/1.2.2/#directives) from [document](https://yaml.org/spec/1.2.2/#documents) [content](https://yaml.org/spec/1.2.2/#nodes)."
It is not usefull in a sigma rule

2023-02-08 05:36 UTC, frack113 commented on rules/windows/process_creation/proc_creation_win_susp_microsoft_onenote_child_process.yml
> +level: medium
we have move all the `level` to the bottom of the rule for consistency.

2023-02-08 18:48 UTC, signus commented
@nasbench - Thank you for the feedback to assist the development of this rule!

I did comment incorrectly on the ProcessCommandLine observed for these child processes spawned from OneNote.
 - `Teams.exe -Embedding` observed from the path `%AppData%\Local\Microsoft\Teams\current\Teams.exe`
 - `"FileCoAuth.exe" -Embedding` observed from the path `%AppData%\Local\Microsoft\OneDrive\<version>\FileCoAuth.exe`.
 
I can update the `Image|endswith` selection to observe consistency with the rest of the rule (e.g. `\Teams.exe`), otherwise only filter on that specific `CommandLine` (assuming public documentation can be found from Microsoft regarding the Embedding component of OneNote, Teams, and FileCoAuth).

2023-02-08 18:54 UTC, nasbench commented
Thanks for the response @signus 

We can add these paths with their specific exact command lines to reduce FP. 

Here is the suggested syntax for consistency

```yml
    filter_teams:
        Image|endswith: '\Local\Microsoft\Teams\current\Teams.exe'
        CommandLine|endswith: '-Embedding'
    filter_onedrive:
        Image|contains: '\Local\Microsoft\OneDrive\'
        Image|endswith: '\FileCoAuth.exe'
        CommandLine|endswith: '-Embedding'
```

Also please pull from master the latest version as the filename you're trying has been modified :)

If your branch isn't protected I can do that for you.

2023-02-09 13:37 UTC, nasbench approved these changes

2023-02-09 13:47 UTC, nasbench commented
@signus I went ahead and applied the suggestions :) 

Thanks again for your contribution.

2023-02-09 13:49 UTC, merged