Create proc_creation_macos_suspicious_applet_behaviour.yml
SigmaHQ/sigma pull request #4126
Opened 2023-03-20 17:35 UTC by D4rkCiph3r

### Summary of the Pull Request
New rule for suspicious applet/OSA behaviour

### Detailed Description of the Pull Request / Additional Comments
This rule detects suspicious applet or command-line OSA behaviour probably dropped by malware into legitimate app's "/Contents/MacOS/" directory.
Refer: https://redcanary.com/blog/mac-application-bundles/ (XCSSET)

### Example Log Event
NA

### Fixed Issues
NA

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

2023-03-21 05:48 UTC, frack113 requested changes
I just remove the space

2023-03-21 05:48 UTC, frack113 commented on rules/macos/process_creation/proc_creation_macos_suspicious_applet_behaviour.yml
> +            - '/applet '
```suggestion
            - '/applet'
```

2023-03-21 05:48 UTC, frack113 commented on rules/macos/process_creation/proc_creation_macos_suspicious_applet_behaviour.yml
> +            - '/osascript '
```suggestion
            - '/osascript'
```

2023-03-22 05:39 UTC, frack113 approved these changes

2023-03-22 05:46 UTC, frack113 commented on rules/macos/process_creation/proc_creation_macos_suspicious_applet_behaviour.yml
> +title: Suspicious Applet Behaviour
```suggestion
title: Suspicious osacompile Run by Applet or Osascript
```

2023-03-22 05:46 UTC, frack113 commented on rules/macos/process_creation/proc_creation_macos_suspicious_applet_behaviour.yml
> +description: Detects suspicious applet or command-line OSA behaviour probably dropped by malware into legitimate apps /Contents/MacOS/ directory
```suggestion
description: | 
    Detects suspicious applet or osascript started a command-line with osacompile.
    Malware can use legitimate apps /Contents/MacOS/ directory to drop the payload
```

2023-04-03 10:17 UTC, nasbench approved these changes

2023-04-03 10:27 UTC, merged