Added support for another way of  execution of netsh
SigmaHQ/sigma pull request #4148
Opened 2023-03-29 11:42 UTC by swachchhanda000

Currently this rule cannot detect if netsh command is issued as "netsh I p a v l=8001 listena=127.0.0.1 connectp=80 c=192.168.1.1". So adding the support

2023-03-29 12:16 UTC, nasbench commented
Hi,

I believe before creating this PR you got a template saying something like this

<img width="792" alt="image" src="https://user-images.githubusercontent.com/8741929/228531993-f8c17c87-5164-42d7-893d-001dbd667697.png">

Please consider filling it so that I can review your PR in a timely manner.

Also use `#`to indicate example comments.

And use spaces between the flags to increase atom size

2023-04-05 11:38 UTC, nasbench requested changes
Can you also please disable the "protected branch" so I can apply suggestions more easily?

2023-04-05 11:38 UTC, nasbench commented on rules/windows/process_creation/proc_creation_win_netsh_port_forwarding.yml
> +            - 'v'
```suggestion
        CommandLine|contains|all:
            # Example: netsh I p a v l=8001 listena=127.0.0.1 connectp=80 c=192.168.1.1
            - 'i ' # interface               
            - 'p ' # portproxy
            - 'a ' # add
            - 'v ' # v4tov4
```

2023-04-05 11:38 UTC, nasbench commented on rules/windows/process_creation/proc_creation_win_netsh_port_forwarding.yml
> +modified: 2023/03/29
```suggestion
modified: 2023/04/05
```

2023-04-12 10:44 UTC, nasbench approved these changes

2023-04-20 09:38 UTC, nasbench commented
cc @phantinuss fyi

2023-04-20 10:10 UTC, phantinuss approved these changes

2023-04-20 10:10 UTC, phantinuss commented on rules/windows/process_creation/proc_creation_win_netsh_port_forwarding.yml
> +modified: 2023/04/05
```suggestion
modified: 2023/04/20
```

2023-04-20 10:30 UTC, merged