Update win_defender_disabled.yml
SigmaHQ/sigma pull request #4208
Opened 2023-04-28 14:24 UTC by securepeacock

### Summary of the Pull Request

Added 3002 event

### Detailed Description of the Pull Request / Additional Comments

Added event 3002 as found in the recent Microsoft report.

### Example Log Event
![Screenshot 2023-04-28 at 10 23 19 AM](https://user-images.githubusercontent.com/92804416/235174089-d49356a4-4b96-416b-aaef-125d4217c50d.png)

### Fixed Issues

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

2023-05-01 08:55 UTC, frack113 requested changes

2023-05-01 08:55 UTC, frack113 commented on rules/windows/builtin/windefend/win_defender_disabled.yml
>  modified: 2022/12/06
```suggestion
modified: 2023/05/01
```

2023-05-01 14:50 UTC, nasbench commented on rules/windows/builtin/windefend/win_defender_disabled.yml
>  modified: 2022/12/06
No need for this, I will will replace this addition by the one we have internally.

2023-05-02 23:15 UTC, nasbench approved these changes

2023-05-02 23:33 UTC, merged