Permiso p0-LUCR-1 (aka GUI-vil)
SigmaHQ/sigma pull request #4294
Opened 2023-06-06 21:17 UTC by danielbohannon

### Summary of the Pull Request

Adding Sigma rules outlined in the following blog post associated with named cloud-focused threat actor p0-LUCR-1 (aka GUI-vil): https://permiso.io/blog/s/unmasking-guivil-new-cloud-threat-actor

### Detailed Description of the Pull Request / Additional Comments

Detects S3 Browser utility creating Inline IAM Policy containing default S3 bucket name placeholder value of <YOUR-BUCKET-NAME>.

### Example Log Event

Example requestParameters value from iam:PutUserPolicy event in CloudTrail logs:

{
	"userName": "FileBackupAccount",
	"policyName": "dq",
	"policyDocument": "{\\r\\n  \\"Statement\\": [\\r\\n    {\\r\\n      \\"Effect\\": \\"Allow\\",\\r\\n      \\"Action\\": \\"s3:GetObject\\",\\r\\n      \\"Resource\\": \\"arn:aws:s3:::<YOUR-BUCKET-NAME>/*\\",\\r\\n      \\"Condition\\": {}\\r\\n    }\\r\\n  ]\\r\\n}"
}

### Fixed Issues

N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

2023-06-23 08:15 UTC, nasbench requested changes

2023-06-23 08:15 UTC, nasbench commented on rules/cloud/aws/aws_iam_s3browser_templated_s3_bucket_policy_creation.yml
> +        requestParameters|contains: '"arn:aws:s3:::<YOUR-BUCKET-NAME>/*"'
I think you meant this `<YOUR-BUCKET-NAME>` as a place holder? If so then you can either use a wildcard directly or we can transfer this rule to a placeholder rule.

2023-06-23 08:15 UTC, nasbench commented on rules/cloud/aws/aws_iam_s3browser_templated_s3_bucket_policy_creation.yml
> +    condition: selection_source and filter_tooling and filter_policy_resource and filter_policy_action and filter_policy_effect
You're using an `and` so the `filter_*` are not meant to exclude something but rather to include it? If so then you can group them in the same selection.

2023-08-23 13:08 UTC, nasbench commented on rules/cloud/aws/aws_iam_s3browser_templated_s3_bucket_policy_creation.yml
> +    condition: selection_source and filter_tooling and filter_policy_resource and filter_policy_action and filter_policy_effect
I assumed its all "and" based on the logic of the blog

2023-08-23 13:08 UTC, nasbench approved these changes

2023-08-24 10:00 UTC, phantinuss approved these changes

2023-08-24 10:00 UTC, phantinuss commented on rules/cloud/aws/aws_iam_s3browser_templated_s3_bucket_policy_creation.yml
> +description: Detects S3 Browser utility creating Inline IAM Policy containing default S3 bucket name placeholder value of "<YOUR-BUCKET-NAME>".
```suggestion
description: Detects S3 browser utility creating Inline IAM policy containing default S3 bucket name placeholder value of "<YOUR-BUCKET-NAME>".
```

2023-08-24 10:00 UTC, phantinuss commented on rules/cloud/aws/aws_iam_s3browser_templated_s3_bucket_policy_creation.yml
> +    - Valid usage of S3 Browser with accidental creation of default Inline IAM Policy without changing default S3 bucket name placeholder value
```suggestion
    - Valid usage of S3 browser with accidental creation of default Inline IAM policy without changing default S3 bucket name placeholder value
```

2023-08-24 10:21 UTC, merged