Create aws_disable_bucket_versioning.yml
SigmaHQ/sigma pull request #4523
Opened 2023-10-27 16:13 UTC by sj-sec

### Summary of the Pull Request

This detection alerts when a threat actor disable AWS S3 bucket versioning. This tactic prohibits victims from restoring any impacted S3 objects and is a common technique used in real world AWS S3 ransomware and extortion incidents. 

### Changelog
N/A

### Example Log Event

{
    "eventVersion": "1.09",
    "userIdentity": {
        "type": "IAMUser",
        "principalId": "AIDA[REDACTED]",
        "arn": "arn:aws:iam::[REDACTED]:user/Admin",
        "accountId": "[REDACTED]",
        "accessKeyId": "[REDACTED]",
        "userName": "Admin",
        "sessionContext": {
            "attributes": {
                "creationDate": "2023-10-27T13:59:36Z",
                "mfaAuthenticated": "true"
            }
        }
    },
    "eventTime": "2023-10-27T14:01:46Z",
    "eventSource": "[s3.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__s3.amazonaws.com&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=S2f_KC8VUGBUG_uY6EuH0nwTqTPUO63PLSzVmyfn9Dg&m=qyrgyDrpytajkt2gsxejVmNho2E8PoaagvyYKOylN_nivZHXPZs7VDSSoxC7ZUjP&s=uOvIyii76sg7ajPZHnoo4IZViznZguiVvrysMjH9gJ8&e=)",
    "eventName": "PutBucketVersioning",
    "awsRegion": "us-east-1",
    "sourceIPAddress": "[REDACTED]",
    "userAgent": "[S3Console/0.4, aws-internal/3 aws-sdk-java/1.12.488 Linux/5.10.196-163.743.amzn2int.x86_64 OpenJDK_64-Bit_Server_VM/25.372-b08 java/1.8.0_372 vendor/Oracle_Corporation cfg/retry-mode/standard]",
    "requestParameters": {
        "bucketName": "[REDACTED]",
        "Host": "[s3.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__s3.amazonaws.com&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=S2f_KC8VUGBUG_uY6EuH0nwTqTPUO63PLSzVmyfn9Dg&m=qyrgyDrpytajkt2gsxejVmNho2E8PoaagvyYKOylN_nivZHXPZs7VDSSoxC7ZUjP&s=uOvIyii76sg7ajPZHnoo4IZViznZguiVvrysMjH9gJ8&e=)",
        "versioning": "",
        "VersioningConfiguration": {
            "Status": "Suspended",
            "xmlns": "[http://s3.amazonaws.com/doc/2006-03-01/](https://urldefense.proofpoint.com/v2/url?u=http-3A__s3.amazonaws.com_doc_2006-2D03-2D01_&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=S2f_KC8VUGBUG_uY6EuH0nwTqTPUO63PLSzVmyfn9Dg&m=qyrgyDrpytajkt2gsxejVmNho2E8PoaagvyYKOylN_nivZHXPZs7VDSSoxC7ZUjP&s=CHR1bWGV-P1QAtDRG7pEhI2DNm23v1zdaPCl10LEerU&e=)"
        }
    },
    "responseElements": null,
    "additionalEventData": {
        "SignatureVersion": "SigV4",
        "CipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "bytesTransferredIn": 125,
        "AuthenticationMethod": "AuthHeader",
        "x-amz-id-2": "liRp5W6YkgGvinnVqvyON6Q/pAEnWT3/f9p25Upq5etFUWX34fwDsMONKO/Ou8FQMti1bPSzmOY=",
        "bytesTransferredOut": 0
    },
    "requestID": "10S4QJVQS0R6ZNDP",
    "eventID": "5876d44b-1d20-4c35-9e9b-e33cfd1df573",
    "readOnly": false,
    "resources": [
        {
            "accountId": "[REDACTED]",
            "type": "AWS::S3::Bucket",
            "ARN": "[REDACTED]"
        }
    ],
    "eventType": "AwsApiCall",
    "managementEvent": true,
    "recipientAccountId": "[REDACTED]",
    "vpcEndpointId": "vpce-f40dc59d",
    "eventCategory": "Management",
    "tlsDetails": {
        "tlsVersion": "TLSv1.2",
        "cipherSuite": "ECDHE-RSA-AES128-GCM-SHA256",
        "clientProvidedHostHeader": "[s3.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__s3.amazonaws.com&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=S2f_KC8VUGBUG_uY6EuH0nwTqTPUO63PLSzVmyfn9Dg&m=qyrgyDrpytajkt2gsxejVmNho2E8PoaagvyYKOylN_nivZHXPZs7VDSSoxC7ZUjP&s=uOvIyii76sg7ajPZHnoo4IZViznZguiVvrysMjH9gJ8&e=)"
    }
}

### Fixed Issues
N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/sigmahq_conventions.md)

2023-10-27 16:50 UTC, nasbench commented
Hey @sj-sec and thanks for this first contribution and welcome to the Sigma community :)

I'll review the rule in a bit. Also don't worry about the test failing, I'll get that fixed too.

Cheers.

2023-10-27 17:24 UTC, sj-sec commented
Thanks @nasbench happy to be here! I have plenty more AWS rules to submit :)

2023-10-28 00:44 UTC, nasbench approved these changes

2023-10-28 11:16 UTC, frack113 requested changes

2023-10-28 11:16 UTC, frack113 commented on rules/cloud/aws/cloudtrail/aws_disable_bucket_versioning.yml
> +        eventSource: s3.amazonaws.com
```suggestion
        eventSource|contains: s3.amazonaws.com
```
From the log 
```json
"eventSource": "[s3.amazonaws.com](https://urldefense.proofpoint.com/v2/url?u=http-3A__s3.amazonaws.com&d=DwMFaQ&c=V9IgWpI5PvzTw83UyHGVSoW3Uc1MFWe5J8PTfkrzVSo&r=S2f_KC8VUGBUG_uY6EuH0nwTqTPUO63PLSzVmyfn9Dg&m=qyrgyDrpytajkt2gsxejVmNho2E8PoaagvyYKOylN_nivZHXPZs7VDSSoxC7ZUjP&s=uOvIyii76sg7ajPZHnoo4IZViznZguiVvrysMjH9gJ8&e=)",
```

2023-10-28 12:36 UTC, frack113 approved these changes

2023-10-28 17:00 UTC, frack113 approved these changes

2023-10-28 23:17 UTC, merged

2023-10-28 23:17 UTC, nasbench commented
Thanks once again @sj-sec for this contribution and can't wait to see more AWS goodness from you :)