New Rule: RDP Originating From Domain Controller
SigmaHQ/sigma pull request #4839
Opened 2024-04-30 13:50 UTC by joshnck

### Summary of the Pull Request

Added a new rule to identify outbound RDP connections from a domain controller using placeholders. 

### Changelog

New: net_connection_win_rdp_from_dc.yml

### Example Log Event
>  ConnectionDirection: 0
   ConnectionFlags: 0
   ContextBaseFileName: mstsc.exe
   ContextProcessId: xxx
   ContextTimeStamp: xxx
   EventOrigin: 1
   InContext: 0
   LocalAddressIP4: xxxx
   LocalPort: 51464
   Protocol: 6
   RemoteAddressIP4: xxxx
   RemoteAddressString: xxxx:3389
   RemotePort: 3389

### Note on Pipelines:
I use the following for my placeholders allowing me to pull either hostname or IP based on need. I'm not sure if we have standardized the conventions on placeholders in Sigma rules yet, but this is my recommendation:

```yaml
name: placeholders
priority: 10
transformations:

### Domain Controllers
  - id: domain_controller_hostname
    type: query_expression_placeholders
    include:
      - domain_controller_hostnames
    expression: "[| inputlookup domaincontrollers | rename host as {field}]"
  - id: domain_controller_ips
    type: query_expression_placeholders
    include:
      - domain_controller_ips
    expression: "[| inputlookup domaincontrollers | rename ip as {field}]"
```    
Allowing this to convert to:
`DestinationPort=3389 [| inputlookup domaincontrollers | rename host as host] NOT Image="Microsoft.Tri.Sensor.exe" | table host,aid,RemotePort,ContextBaseFileName` in SPL

2024-05-01 05:46 UTC, frack113 requested changes

2024-05-01 05:46 UTC, frack113 commented on rules-placeholder/windows/network_connection/net_connection_win_rdp_from_dc.yml
> +        ComputerName|expand: '%domain_controller_hostnames%'
```suggestion
        Computer|expand: '%domain_controller_hostnames%'
```
In the windows event it is `Computer`

2024-05-02 15:55 UTC, frack113 approved these changes
LGTM

2024-05-05 06:00 UTC, frack113 commented on rules-placeholder/windows/network_connection/net_connection_win_rdp_from_dc.yml
> +        DestinationPort: 3389
```suggestion
    selection_cnx:
        Initiated: 'True'
        DestinationPort: 3389
```

2024-05-10 14:25 UTC, nasbench approved these changes

2024-05-10 14:32 UTC, merged