Add Sigma rule for CVE-2024-38063 IPv6 memory corruption detection
SigmaHQ/sigma pull request #4988
Opened 2024-08-28 09:28 UTC by zenzue

add rule for contribute

### Summary of the Pull Request
This pull request introduces a new Sigma rule designed to detect exploitation attempts associated with CVE-2024-38063. The rule identifies specific network traffic patterns that may indicate an attempt to exploit memory corruption vulnerabilities in systems using IPv6.

### Changelog
new: CVE-2024-38063_ipv6_memory_corruption_detection.yml - Adds a rule for detecting suspicious IPv6 packet patterns that may indicate exploitation of CVE-2024-38063.

### Example Log Event
```yaml
{
    "protocol": "IPv6",
    "events": {
        "FragmentationEvent": true,
        "AnomalousIPv6OptionHeaderEvent": true
    },
    "packet_length": "1337",
    "src_ip": "2001:db8::1",
    "dst_ip": "2001:db8::2",
    "info": "Detected packet with potentially malicious fragmentation and option headers"
}

### Fixed Issues
https://techcommunity.microsoft.com/t5/windows-server-for-it-pro/cve-2024-38063-disabling-ipv6-binding-fix-or-not/td-p/4220374

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/)

2024-08-29 20:50 UTC, nasbench requested changes

2024-08-29 20:50 UTC, nasbench commented on rules-emerging-threats/2024/Exploits/CVE-2024-38063/CVE-2024-38063_ipv6_memory_corruption_detection.yml
> +    product: network_monitoring
Which product is this?

2024-08-31 17:57 UTC, zenzue commented on rules-emerging-threats/2024/Exploits/CVE-2024-38063/CVE-2024-38063_ipv6_memory_corruption_detection.yml
> +    product: network_monitoring
ah sorry 4 my bad 
i got it from trend_micro_xdr
but  can work with other network monitoring products
that why i do not add as 
```
logsource:
    category: network_traffic
    product: trend_micro_xdr
```

2024-09-02 08:04 UTC, nasbench commented on rules-emerging-threats/2024/Exploits/CVE-2024-38063/CVE-2024-38063_ipv6_memory_corruption_detection.yml
> +    product: network_monitoring
Can you give me another example from another product. Else this would be a specific rule to trend micro XDR with its own specific field.

Because for this rule to be used, the fields needs to be mapped based on the logsource and then converted using a backend.

Aren't the name of the events unique to TrendMicro convention

I need at least 1 other product that has this coverage for this rule to make sense for "everybody else".

2024-09-22 17:30 UTC, nasbench commented on rules-emerging-threats/2024/Exploits/CVE-2024-38063/CVE-2024-38063_ipv6_memory_corruption_detection.yml
> +    product: network_monitoring
@zenzue ping

2024-09-23 05:03 UTC, zenzue commented
Sorry,
in this station
i am working as a volunteer for rescue in our country about Flooding places.
I will update it soon ...

best.

On Mon, Sep 23, 2024 at 12:00 AM Nasreddine Bencherchali <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> rules-emerging-threats/2024/Exploits/CVE-2024-38063/CVE-2024-38063_ipv6_memory_corruption_detection.yml
> <https://github.com/SigmaHQ/sigma/pull/4988#discussion_r1770599391>:
>
> > +    category: network_traffic
> +    product: network_monitoring
>
> @zenzue <https://github.com/zenzue> ping
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SigmaHQ/sigma/pull/4988#discussion_r1770599391>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AETA5LFEDHKJAWWXIE5E3Z3ZX35DPAVCNFSM6AAAAABNH3O6KKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMRQHA4TGNJTHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-03-05 00:05 UTC, nasbench commented
Closing this for now as a stale PR. The author can re-open the PR after addressing the comments.

2025-03-05 00:05 UTC, closed without merging