DeleteSAMLProvider AWS
SigmaHQ/sigma pull request #5015
Opened 2024-09-20 08:06 UTC by saakovv

Monitoring DeleteSAMLProvider events separately from UpdateSAMLProvider makes sense, since these actions have different contexts, risks, and consequences. Tracking both types of events allows you to more fully control changes in the configuration of SAML providers and respond faster to potential threats.

### Summary of the Pull Request

### Changelog

### Example Log Event

### Fixed Issues

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/)

2024-12-14 10:35 UTC, frack113 requested changes

2024-12-14 10:35 UTC, frack113 commented on rules/cloud/aws/cloudtrail/aws_delete_saml.yml
> +level: medium
HI,
I am looking for related malicious activity but I don't find it. 
In view of the false positives, it's more of a `low` rule.

2024-12-16 21:31 UTC, saakovv commented on rules/cloud/aws/cloudtrail/aws_delete_saml.yml
> +level: medium
An attacker can disable SAML, for example, for employees of the information security department. At one of the recent pentests, I saw that the attackers did things that made it difficult for the defense team to work. You simply cannot log into your account via SAML and this is very critical at the time of the attack.

2024-12-16 21:37 UTC, saakovv commented on rules/cloud/aws/cloudtrail/aws_delete_saml.yml
> +level: medium
<img width="1663" alt="Снимок экрана 2024-12-16 в 11 36 52 PM" src="https://github.com/user-attachments/assets/46228e91-1a7d-401c-bd89-e4863b496eb9" />
@frack113 it looks like this

2024-12-17 05:23 UTC, frack113 commented on rules/cloud/aws/cloudtrail/aws_delete_saml.yml
> +level: medium
Thanks for the clarification.

2024-12-17 05:23 UTC, frack113 approved these changes

2024-12-19 19:24 UTC, nasbench approved these changes

2024-12-19 19:30 UTC, merged