Update rule Powershell Exfiltration Over SMTP considering the attachm…
SigmaHQ/sigma pull request #5052
Opened 2024-10-15 14:20 UTC by dan21san

…ent flag

### Summary of the Pull Request

Updating the `posh_ps_send_mailmessage` rule by considering the `Attachments` flag according to the documentation. 
The rule wants to detect exfiltration, so I suggest considering the -Attachments parameter. 

In my case, this avoids a lot of FP.

### Changelog

update: Potential Data Exfiltration Over SMTP Via Send-MailMessage Cmdlet - Add the "-Attachments" flag to the logic in order to reduce false positives.

### Example Log Event
N/A

### Fixed Issues
N/A

### SigmaHQ Rule Creation Conventions

- If your PR adds new rules, please consider following and applying these [conventions](https://github.com/SigmaHQ/sigma-specification/blob/main/sigmahq/)

2024-10-21 11:26 UTC, frack113 requested changes

2024-10-21 11:26 UTC, frack113 commented on rules/windows/powershell/powershell_script/posh_ps_send_mailmessage.yml
> +date: 2024-10-15
```suggestion
date: 2022-09-26
modified: 2024-10-15
```

2024-10-21 11:34 UTC, frack113 approved these changes

2024-11-01 09:16 UTC, nasbench approved these changes

2024-11-01 09:20 UTC, merged